
name: Sample Action
on:
  push:
    branches: [ "master", "ma*", "stage" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master", "stage" ]
permissions:
  contents: read
jobs:
  test-job:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3