
name: Sample Action
on:
  push:
    branches: [ "master", "ma*", "stage" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master", "stage" ]
permissions:
  contents: read
jobs:
  test-job:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 
        with:
          fetch-depth: 0
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@b87d48154a87a85666003575337e27b8cd65f691 #v1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # https://github.community/t5/GitHub-Actions/Workflow-is-failing-if-no-job-can-be-ran-due-to-condition/m-p/38186#M3250
