name: Misc Scan

on:
  push:
    branches: [ "master", "ma*" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  misc-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Misc Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      
      - uses: actions/checkout@v4
      - run: echo "this is a sample step"
   
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0
        with:
          client-id: ${{ secrets.CIMON_CLIENT_ID }}
          secret: ${{ secrets.CIMON_SECRET }}
          prevent: true
          allowed-hosts: >
            gitlab.com
            cycode.com
            storage.googleapis.com
          #allowed-ips: >
          #  34.121.34.97
      
      - name: Connect to Amazon Forbidden
        run: curl amazon.com
      - name: Connect to GitLab 
        run: curl gitlab.com
      - name: Connect to Cycode
        run: curl cycode.com


    
